export default {
  EMPLOYEE_LOAD_START: "EMPLOYEE_LOAD_START",
  EMPLOYEE_LOAD_SUCCESS: "EMPLOYEE_LOAD_SUCCESS",
  EMPLOYEE_LOAD_ERROR: "EMPLOYEE_LOAD_ERROR",
  SINGLE_EMPLOYEE_LOAD_SUCCESS: "SINGLE_EMPLOYEE_LOAD_SUCCESS",
};
